### PR TITLE
Ensure large number are properly parsed

### LINKED ISSUE #1: Unmarshal response  from Int to Interface will be scientific notation
Bug Report

1. Minimal reproduce step (Required)

The int of response will be scientific notation because of golang json unmarshal use float64 to get number.

2. What did you expect to see? (Required)

Int should not be unmarshal with float64

Version: v0.0.0-20200315235754-52a754895136

### PR DESCRIPTION
**Pull request by troywinter**
Marshal json using json.Encoder UseNumber option to parse large number, prevent incorrect convert to float64 then back to int in original implementation, which is not idiomatic in go.

### CODE REVIEW

File: pinot-client-go/response_test.go [hunk 1]
```diff
@@ -11,7 +12,10 @@ import (
...
-	err := json.Unmarshal(respBytes, &brokerResponse)
+	decoder := json.NewDecoder(bytes.NewReader(respBytes))
+	decoder.UseNumber()
+	err := decoder.Decode(&brokerResponse)
+	//err := json.Unmarshal(respBytes, &brokerResponse)
```
Comment (xiangfu0) [inline pinot-client-go/response_test.go]: delete this line

File: pinot-client-go/jsonAsyncHTTPClientTransport.go [hunk 2]
```diff
@@ -48,14 +48,15 @@ func (t jsonAsyncHTTPClientTransport) execute(brokerAddress string, query *Reque
 			return nil, err
 		}
 		var brokerResponse BrokerResponse
-		err = json.Unmarshal(bodyBytes, &brokerResponse)
-		if err != nil {
+		decoder := json.NewDecoder(bytes.NewReader(bodyBytes))
+		decoder.UseNumber()
+		if err = decoder.Decode(&brokerResponse); err != nil {
```
Comment (xiangfu0) [inline pinot-client-go/jsonAsyncHTTPClientTransport.go]: shall we make this a util function and use the function here and in the test?

**Review by xiangfu0 — APPROVED** [review]
lgtm otherwise

**Comment by xiangfu0** [comment]
Thanks for fixing this!
